// Generated by gencpp from file xx_msgs/Flag.msg
// DO NOT EDIT!


#ifndef XX_MSGS_MESSAGE_FLAG_H
#define XX_MSGS_MESSAGE_FLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xx_msgs
{
template <class ContainerAllocator>
struct Flag_
{
  typedef Flag_<ContainerAllocator> Type;

  Flag_()
    : flag()
    , num_16b(0)
    , arrary_num_16b()  {
      arrary_num_16b.assign(0);
  }
  Flag_(const ContainerAllocator& _alloc)
    : flag(_alloc)
    , num_16b(0)
    , arrary_num_16b()  {
  (void)_alloc;
      arrary_num_16b.assign(0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flag_type;
  _flag_type flag;

   typedef int16_t _num_16b_type;
  _num_16b_type num_16b;

   typedef boost::array<int16_t, 12>  _arrary_num_16b_type;
  _arrary_num_16b_type arrary_num_16b;





  typedef boost::shared_ptr< ::xx_msgs::Flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xx_msgs::Flag_<ContainerAllocator> const> ConstPtr;

}; // struct Flag_

typedef ::xx_msgs::Flag_<std::allocator<void> > Flag;

typedef boost::shared_ptr< ::xx_msgs::Flag > FlagPtr;
typedef boost::shared_ptr< ::xx_msgs::Flag const> FlagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xx_msgs::Flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xx_msgs::Flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xx_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xx_msgs': ['/home/xx/begin_ws/src/xx_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xx_msgs::Flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xx_msgs::Flag_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xx_msgs::Flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xx_msgs::Flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xx_msgs::Flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xx_msgs::Flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xx_msgs::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca2b3a8f88ad832e39fae4ff8cd84ffc";
  }

  static const char* value(const ::xx_msgs::Flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca2b3a8f88ad832eULL;
  static const uint64_t static_value2 = 0x39fae4ff8cd84ffcULL;
};

template<class ContainerAllocator>
struct DataType< ::xx_msgs::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xx_msgs/Flag";
  }

  static const char* value(const ::xx_msgs::Flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xx_msgs::Flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string flag\n\
int16 num_16b\n\
int16[12]  arrary_num_16b\n\
";
  }

  static const char* value(const ::xx_msgs::Flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xx_msgs::Flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.num_16b);
      stream.next(m.arrary_num_16b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xx_msgs::Flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xx_msgs::Flag_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flag);
    s << indent << "num_16b: ";
    Printer<int16_t>::stream(s, indent + "  ", v.num_16b);
    s << indent << "arrary_num_16b[]" << std::endl;
    for (size_t i = 0; i < v.arrary_num_16b.size(); ++i)
    {
      s << indent << "  arrary_num_16b[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.arrary_num_16b[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XX_MSGS_MESSAGE_FLAG_H
